### ISSUE TITLE
Remove public setting for video, but transcript still in admin panel

### ISSUE THREAD

**Issue by binarybottle** [ChildMindInstitute/crisislogger-gallery-frontend#4]
<img width="749" alt="Screen Shot 2020-05-22 at 2 41 49 PM" src="https://user-images.githubusercontent.com/236532/82699396-92041a00-9c3a-11ea-9286-0e07dab92c8e.png">
<img width="1100" alt="Screen Shot 2020-05-22 at 2 42 18 PM" src="https://user-images.githubusercontent.com/236532/82699398-929cb080-9c3a-11ea-844b-c1366e3ade49.png">

**Comment by henry-overton** [comment]
Fixed and pushed.
