### ISSUE TITLE
Make video public in dashboard, add to gallery from admin panel, doesn't show in gallery

### ISSUE THREAD

**Issue by binarybottle** [ChildMindInstitute/crisislogger-gallery-frontend#5]
<img width="1302" alt="Screen Shot 2020-05-22 at 2 45 45 PM" src="https://user-images.githubusercontent.com/236532/82699656-0c349e80-9c3b-11ea-938e-64c9397cb489.png">

**Comment by henry-overton** [comment]
I could see the above video on gallery after change in admin panel
![Screen Shot 2020-05-24 at 1 29 50 PM](https://user-images.githubusercontent.com/63484644/82751823-a2df9780-9dc2-11ea-91bb-73bed5f3701e.png)

Could you please make sure you reloaded the page after change ?
